name = "vec-image-search"
main = "src/index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[images]
binding = "IMAGES"

[ai]
binding = "AI"

[vars]
QDRANT_URL = "https://vec.kufof.uk"
DOMAIN = "search.kufof.uk"

routes = [
  { pattern = "search.kufof.uk", custom_domain = true }
]
